version: '3.8'

services:
  # 云端极客沙盒环境
  code-playground:
    image: nginx:alpine
    container_name: bitpulse-code
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/usr/share/nginx/html:ro