version: '3.8'

services:
  # 比特脉冲中央主页服务
  homepage:
    image: nginx:alpine
    container_name: bitpulse-homepage
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/usr/share/nginx/html:ro
      - ./nginx-conf:/etc/nginx/conf.d:ro