# 1. 拦截 www 域名并强行重定向到主域名
server {
    listen 80;
    server_name www.bitpulse.club;
    return 301 https://bitpulse.club$request_uri;
}

# 2. 个人科技感导航主页服务
server {
    listen 80;
    server_name bitpulse.club;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
}

# 3. LobeChat AI 聊天平台转发
server {
    listen 80;
    server_name chat.bitpulse.club;

    location / {
        proxy_pass http://172.17.0.1:3210;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# 4. 新增：Alist 私人云网盘转发
server {
    listen 80;
    server_name pan.bitpulse.club;

    location / {
        proxy_pass http://172.17.0.1:5244;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # 允许上传大文件（最大 5GB），防止大文件上传时报 413 错误
        client_max_body_size 5000m; 
    }
}


# 5. 云端极客沙盒转发
server {
    listen 80;
    server_name code.bitpulse.club;

    location / {
        proxy_pass http://172.17.0.1:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}


# 6. Authentik 统一认证中心
server {
    listen 80;
    server_name passport.bitpulse.club;

    location / {
        proxy_pass http://172.17.0.1:9000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # 支持 WebSocket 协议 (Authentik 后台强依赖)
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}